name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build Docker Image
      run: docker build . --tag ryuyanninja/steam-hardware-survey:latest
    - name: Push Docker Image
      run: docker push ryuyanninja/steam-hardware-survey:latest