name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build Docker Image
      run: docker build --build-arg SITE_ROOT_ARG=${{ secrets.SITE_ROOT }} --tag ryuyandev/steam-hardware-survey:latest .
    - name: Push Docker Image
      run: docker push ryuyandev/steam-hardware-survey:latest